taskkill /f /im googledrivesync.exe
taskkill /f /im chrome.exe
taskkill /f /im notepad.exe
taskkill /f /im sublime.exe
taskkill /f /im franz.exe
taskkill /f /im origin.exe
taskkill /f /im steam.exe
taskkill /f /im filezilla.exe
taskkill /f /im slack.exe
